// Scotland 2026 — itinerary data
// Highland Games are integrated as a `games` note inside the relevant day,
// shown as a subtle contextual badge — not a separate section.

export const DAYS = [
  {
    day: 1, date: "Dom 26 jul",
    title: "Llegada — Edimburgo",
    sub: "Aterrizaje 09:30 · Old Town · Royal Mile · Grassmarket",
    driving: "0 km", overnight: "Edimburgo",
    accent: "#1e3d2a",
    highlights: [
      { i: "✈", t: "Aterrizaje EDI 09:30 — recoge el coche de alquiler en el aeropuerto" },
      { i: "🏰", t: "Castillo de Edimburgo (tarde) — reserva online imprescindible" },
      { i: "🥃", t: "Paseo por el Royal Mile hasta el Palacio de Holyrood" },
      { i: "🌆", t: "Barrio Grassmarket para cenar y primer pub escocés" },
    ],
    tickets: [
      { n: "Castillo de Edimburgo", p: "~21 £/p", must: true, url: "https://www.edinburghcastle.scot" },
      { n: "Palacio de Holyrood", p: "~17 £/p", must: false, url: "https://www.rct.uk/visit/palace-of-holyroodhouse" },
    ],
    hotels: [
      { n: "Hotel Indigo Edinburgh – Royal Mile", s: 4, p: "90–130 €", note: "Diseño contemporáneo, ubicación perfecta en el Royal Mile.", top: true, url: "https://www.ihg.com" },
      { n: "The Witchery by the Castle", s: 5, p: "140–180 €", note: "Icónico gótico victoriano, solo 9 suites. Reserva pronto.", url: "https://www.thewitchery.com" },
      { n: "Grassmarket Hotel", s: 3, p: "70–100 €", note: "Ambiente animado en el corazón del Old Town.", url: "https://www.grassmarkethotel.co.uk" },
    ],
    rests: [
      { n: "Timberyard", ty: "Escocés moderno", p: "€€€", note: "Uno de los mejores de la ciudad. Producto local de temporada." },
      { n: "Café Royal", ty: "Mariscos · pub victoriano", p: "€€", note: "Interior del siglo XIX impresionante. Ostras y cerveza artesanal." },
      { n: "The Grain Store", ty: "Brasserie escocesa", p: "€€", note: "Buena carne y pescado local, precio razonable." },
    ],
    mapCenter: [55.95, -3.19], mapZoom: 13,
    pts: [
      { n: "Aeropuerto EDI", lat: 55.9508, lng: -3.3615 },
      { n: "Castillo de Edimburgo", lat: 55.9486, lng: -3.1999 },
      { n: "Royal Mile", lat: 55.9503, lng: -3.1883 },
      { n: "Grassmarket", lat: 55.9462, lng: -3.1956 },
    ],
  },
  {
    day: 2, date: "Lun 27 jul",
    title: "Edimburgo → Glasgow",
    sub: "Arthur's Seat · West End · Commonwealth Games (atletismo)",
    driving: "~75 km · 1h", overnight: "Glasgow",
    accent: "#12243a",
    // Natural Highland Games note — integrated contextually
    gamesNote: {
      emoji: "🏅",
      text: "Commonwealth Games Glasgow (27 jul–1 ago) — Athletics en Scotstoun Stadium. Llegas hoy, puedes coger entradas para esta tarde o mañana.",
      url: "https://www.glasgow2026.com",
      urlLabel: "Entradas oficiales ↗",
    },
    highlights: [
      { i: "🏔", t: "Subida a Arthur's Seat (45 min, vistas 360° sobre Edimburgo)" },
      { i: "🚗", t: "Conducción a Glasgow por la M8 (~1h)" },
      { i: "🏟", t: "Commonwealth Games — atletismo en Scotstoun Stadium (tarde/noche)" },
      { i: "🍺", t: "West End de Glasgow para cenar — Byres Road" },
    ],
    tickets: [
      { n: "Commonwealth Games Atletismo", p: "20–50 £/sesión", must: true, warn: "¡Reserva ya!", url: "https://www.glasgow2026.com" },
      { n: "Arthur's Seat (Holyrood Park)", p: "Gratis", must: false, url: null },
    ],
    hotels: [
      { n: "Kimpton Blythswood Square", s: 5, p: "120–160 €", note: "El mejor de Glasgow, palacete georgiano con spa excelente.", top: true, url: "https://www.kimptonblythswoodsquare.com" },
      { n: "Hotel Indigo Glasgow", s: 4, p: "80–120 €", note: "Buen diseño, zona céntrica, bien conectado al estadio.", url: "https://www.ihg.com" },
      { n: "Grasshoppers Hotel", s: 3, p: "60–90 €", note: "Boutique muy bien valorado, relación calidad-precio excelente.", url: "https://www.grasshoppersglasgow.com" },
    ],
    rests: [
      { n: "Ox and Finch", ty: "Tapas escocesas · sharing", p: "€€", note: "El más de moda en Glasgow. Platos pequeños para compartir." },
      { n: "Cail Bruich", ty: "Fine dining · Michelin ★", p: "€€€", note: "Estrella Michelin. Reserva con mucha antelación." },
      { n: "Ubiquitous Chip", ty: "Escocés clásico · West End", p: "€€", note: "Institución desde 1971. Ambiente único, jardín interior." },
    ],
    mapCenter: [55.865, -4.26], mapZoom: 12,
    pts: [
      { n: "Arthur's Seat, Edimburgo", lat: 55.9442, lng: -3.1611 },
      { n: "Scotstoun Stadium (Commonwealth)", lat: 55.8783, lng: -4.3589 },
      { n: "West End Glasgow", lat: 55.8759, lng: -4.2886 },
    ],
  },
  {
    day: 3, date: "Mar 28 jul",
    title: "Glasgow → Loch Lomond → Glencoe",
    sub: "Los primeros Highlands · Majestuosidad pura",
    driving: "~150 km · 2.5h", overnight: "Glencoe / Fort William",
    accent: "#2a1505",
    highlights: [
      { i: "🏞", t: "Luss (Loch Lomond) — el pueblo más bonito del parque nacional" },
      { i: "🌫", t: "Rannoch Moor — la llanura más salvaje e infinita de Escocia" },
      { i: "🏔", t: "Valle de Glencoe — Three Sisters. La foto del viaje." },
      { i: "🦌", t: "Signal Rock — bosque antiguo con posible avistamiento de ciervos" },
    ],
    tickets: [
      { n: "Glencoe Visitor Centre (NTS)", p: "~7 £/p", must: true, url: "https://www.nts.org.uk/visit/places/glencoe" },
      { n: "Aparcamiento Luss", p: "~3 £", must: false, url: null },
    ],
    hotels: [
      { n: "Kingshouse Hotel", s: 4, p: "110–150 €", note: "Hotel histórico en mitad de Glencoe, vistas espectaculares.", top: true, url: "https://www.kingshousehotel.co.uk" },
      { n: "Glencoe Inn", s: 3, p: "70–100 €", note: "Pub-hotel acogedor en el pueblo de Glencoe.", url: "https://www.glencoeinn.com" },
      { n: "Alexandra Hotel Fort William", s: 3, p: "80–110 €", note: "Si prefieres Fort William (~30 min), vistas al Ben Nevis.", url: null },
    ],
    rests: [
      { n: "Kingshouse Hotel Restaurant", ty: "Escocés highland", p: "€€", note: "Cordero y venado local. Ambiente rústico de montaña." },
      { n: "Glencoe Café", ty: "Café ligero", p: "€", note: "Sopas caseras y tartas para reponer fuerzas." },
      { n: "Lime Tree Fort William", ty: "Escocés moderno", p: "€€€", note: "Mariscos frescos, muy bien valorado en Fort William." },
    ],
    mapCenter: [56.58, -5.0], mapZoom: 9,
    pts: [
      { n: "Luss, Loch Lomond", lat: 56.1026, lng: -4.6365 },
      { n: "Rannoch Moor", lat: 56.6537, lng: -4.7456 },
      { n: "Glencoe — Three Sisters", lat: 56.6818, lng: -5.02 },
      { n: "Kingshouse Hotel", lat: 56.6599, lng: -4.8785 },
    ],
  },
  {
    day: 4, date: "Mié 29 jul",
    title: "Fort William · Ben Nevis · Jacobite Train",
    sub: "El techo de Gran Bretaña · El tren de Harry Potter",
    driving: "~40 km local", overnight: "Fort William",
    accent: "#082018",
    highlights: [
      { i: "⛰", t: "Ben Nevis — senderismo ruta turística (5–7h, 1345m) o vistas desde el valle" },
      { i: "🚂", t: "Jacobite Steam Train — Fort William a Mallaig cruzando el Viaducto de Glenfinnan" },
      { i: "🦞", t: "Mallaig — puerto de pescadores con las mejores gambas de Escocia" },
      { i: "🔒", t: "Neptune's Staircase — la esclusa en escalera más larga del Reino Unido" },
    ],
    tickets: [
      { n: "Jacobite Steam Train", p: "~35–45 £/p ida y vuelta", must: true, warn: "Se agota meses antes. Reserva ya.", url: "https://www.westcoastrailways.co.uk/jacobite" },
      { n: "Ben Nevis (libre acceso)", p: "Gratis · botas impermeables imprescindibles", must: false, url: null },
    ],
    hotels: [
      { n: "The Grange Fort William", s: 4, p: "90–130 €", note: "B&B boutique con vistas al loch. Muy bien valorado.", top: true, url: null },
      { n: "Bank Street Lodge", s: 3, p: "60–80 €", note: "Limpio, bien situado, excelente relación calidad-precio.", url: null },
      { n: "Inverlochy Castle Hotel", s: 5, p: "200–300 €", note: "Para darse un capricho. Castillo convertido en hotel de lujo.", url: "https://www.inverlochycastlehotel.com" },
    ],
    rests: [
      { n: "The Crannog Seafood", ty: "Mariscos · sobre el lago", p: "€€", note: "Mejillones y gambas del día. Imprescindible en Fort William." },
      { n: "Garrison West", ty: "Grill · casual", p: "€€", note: "Buena carne local, ambiente relajado y animado." },
      { n: "Ben Nevis Inn", ty: "Pub · base de montaña", p: "€", note: "Perfecto post-senderismo. En la base del Ben Nevis." },
    ],
    mapCenter: [56.82, -5.11], mapZoom: 11,
    pts: [
      { n: "Ben Nevis", lat: 56.7969, lng: -5.0035 },
      { n: "Estación Fort William (Jacobite)", lat: 56.8191, lng: -5.1073 },
      { n: "Viaducto de Glenfinnan", lat: 56.8726, lng: -5.4308 },
      { n: "Neptune's Staircase, Banavie", lat: 56.8468, lng: -5.1274 },
    ],
  },
  {
    day: 5, date: "Jue 30 jul",
    title: "Fort William → Inverness",
    sub: "Great Glen · Loch Ness · Culloden",
    driving: "~105 km · 1.5h", overnight: "Inverness",
    accent: "#0a1828",
    highlights: [
      { i: "🦕", t: "Castillo de Urquhart a orillas del Loch Ness — busca a Nessie" },
      { i: "⚔", t: "Culloden Battlefield — la última batalla en suelo británico (1746). Muy emotivo." },
      { i: "🏙", t: "Inverness — la capital de los Highlands, paseo por el río Ness" },
      { i: "🛍", t: "Victorian Market — mercado cubierto del siglo XIX" },
    ],
    tickets: [
      { n: "Castillo de Urquhart (HES)", p: "~12 £/p", must: true, url: "https://www.historicenvironment.scot/visit-a-place/places/urquhart-castle" },
      { n: "Culloden Battlefield (NTS)", p: "~14 £/p", must: true, url: "https://www.nts.org.uk/visit/places/culloden" },
    ],
    hotels: [
      { n: "Rocpool Reserve", s: 5, p: "130–200 €", note: "El más glamuroso de Inverness. Boutique, diseño contemporáneo.", top: true, url: "https://www.rocpool.com" },
      { n: "Kingsmills Hotel", s: 4, p: "90–140 €", note: "Casa señorial con spa, a 10 minutos del centro.", url: "https://www.kingsmillshotel.com" },
      { n: "Inverness Palace Hotel & Spa", s: 4, p: "80–120 €", note: "Junto al río Ness, buenas vistas.", url: "https://www.invernesspalacehotel.co.uk" },
    ],
    rests: [
      { n: "Rocpool Restaurant", ty: "Escocés moderno", p: "€€€", note: "El mejor de Inverness. Mariscos y caza. Reserva imprescindible." },
      { n: "The Mustard Seed", ty: "Escocés · iglesia convertida", p: "€€", note: "En una antigua iglesia con vistas al Ness. Gran relación calidad-precio." },
      { n: "Contrast Brasserie", ty: "Brasserie · río Ness", p: "€€", note: "Frente al Ness en el Glenmoriston Hotel." },
    ],
    mapCenter: [57.38, -4.3], mapZoom: 10,
    pts: [
      { n: "Castillo de Urquhart", lat: 57.3228, lng: -4.4419 },
      { n: "Culloden Battlefield", lat: 57.477, lng: -4.0779 },
      { n: "Inverness Centre", lat: 57.4778, lng: -4.2247 },
    ],
  },
  {
    day: 6, date: "Vie 31 jul",
    title: "Inverness → Speyside · Whisky Trail",
    sub: "La meca del single malt escocés",
    driving: "~80 km · 1.5h", overnight: "Speyside",
    accent: "#201000",
    highlights: [
      { i: "🥃", t: "The Macallan — arquitectura espectacular, visita y cata. Reserva imprescindible." },
      { i: "🥃", t: "Glenfarclas — una de las pocas destilerías de familia. Ambiente auténtico." },
      { i: "🏞", t: "Speyside Way — paseo junto al río Spey entre destilerías" },
      { i: "🎶", t: "Charlestown of Aberlour — pueblo encantador con pub de whisky de colección" },
    ],
    tickets: [
      { n: "The Macallan Experience", p: "~25–50 £/p", must: true, warn: "Reserva online imprescindible", url: "https://www.themacallan.com/visit" },
      { n: "Glenfarclas Distillery + Cata", p: "~15 £/p", must: true, url: "https://www.glenfarclas.com/visit" },
    ],
    hotels: [
      { n: "Craigellachie Hotel", s: 4, p: "100–150 €", note: "Victoriano icónico en Speyside. El Quaich Bar tiene 1.000+ referencias de whisky.", top: true, url: "https://www.craigellachiehotel.co.uk" },
      { n: "Mash Tun B&B, Aberlour", s: 4, p: "90–120 €", note: "B&B temático del whisky junto al río Spey.", url: "https://www.mashtun-aberlour.com" },
      { n: "Grant Arms Hotel", s: 3, p: "70–100 €", note: "Hotel histórico con encanto, buen pub.", url: "https://www.grantarmshotel.com" },
    ],
    rests: [
      { n: "The Copper Dog (Craigellachie)", ty: "Pub gourmet · whisky bar", p: "€€", note: "La mejor selección de whiskies de la zona. Comida de pub excelente." },
      { n: "The Mash Tun", ty: "Escocés íntimo", p: "€€", note: "Cenas caseras con productos locales. Ambiente de casa de campo." },
      { n: "Dowans Hotel Restaurant", ty: "Escocés clásico", p: "€€", note: "Junto al Spey, buena relación calidad-precio." },
    ],
    mapCenter: [57.42, -3.25], mapZoom: 11,
    pts: [
      { n: "The Macallan Distillery", lat: 57.4769, lng: -3.2069 },
      { n: "Glenfarclas Distillery", lat: 57.3919, lng: -3.3628 },
      { n: "Aberlour (Speyside Way)", lat: 57.4652, lng: -3.226 },
      { n: "Craigellachie Hotel", lat: 57.4682, lng: -3.2075 },
    ],
  },
  {
    day: 7, date: "Sáb 1 ago",
    title: "Speyside → Isle of Skye",
    sub: "Eilean Donan · Skye Bridge · Old Man of Storr",
    driving: "~220 km · 3h", overnight: "Portree, Isle of Skye",
    accent: "#061828",
    // Newtonmore Highland Games están a solo 30 min de ruta — nota natural al pasar
    gamesNote: {
      emoji: "⚔",
      text: "Newtonmore Highland Games — hoy en The Eilan, Newtonmore (a 30 min de tu ruta hacia Skye). Lanzamiento de caber, gaitas y danza highland. Puedes parar un par de horas de camino.",
      url: "https://newtonmorehighlandgames.co.uk",
      urlLabel: "Ver más ↗",
    },
    highlights: [
      { i: "⚔", t: "Newtonmore Highland Games (de paso, ~30 min fuera de ruta) — ver nota" },
      { i: "🏰", t: "Eilean Donan Castle — el castillo más fotografiado de Escocia (en ruta)" },
      { i: "🌉", t: "Cruzar el Skye Bridge desde Kyle of Lochalsh — momento mágico" },
      { i: "🗿", t: "Old Man of Storr — columna rocosa icónica, ruta ~2h" },
    ],
    tickets: [
      { n: "Eilean Donan Castle", p: "~12 £/p", must: true, url: "https://www.eileandonancastle.com" },
      { n: "Newtonmore Games (si paras)", p: "~10–15 £/p en puerta", must: false, url: "https://newtonmorehighlandgames.co.uk" },
      { n: "Old Man of Storr (aparcamiento)", p: "~3 £", must: false, url: null },
    ],
    hotels: [
      { n: "Skeabost Hotel", s: 4, p: "110–150 €", note: "Casa señorial con jardines al loch. A 10 min de Portree.", top: true, url: "https://www.skeabosthotel.com" },
      { n: "Cuillin Hills Hotel", s: 4, p: "100–140 €", note: "Vistas espectaculares a los Cuillins desde Portree.", url: "https://www.cuillinhillshotel-skye.co.uk" },
      { n: "Portree Hotel", s: 3, p: "70–100 €", note: "Justo en el puerto de Portree, sencillo y con encanto.", url: null },
    ],
    rests: [
      { n: "Sea Breezes, Portree", ty: "Mariscos · sin reservas", p: "€€", note: "El mejor marisco de Skye. Langostas del loch. Llega pronto." },
      { n: "Scorrybreac", ty: "Fine dining · 5 mesas", p: "€€€", note: "Menú degustación de Skye. Reserva con semanas de antelación." },
      { n: "The Bosville, Portree", ty: "Bistró · casual", p: "€€", note: "Buen ambiente, vistas al puerto." },
    ],
    mapCenter: [57.3, -5.8], mapZoom: 9,
    pts: [
      { n: "Newtonmore (Highland Games)", lat: 57.059, lng: -4.1381 },
      { n: "Eilean Donan Castle", lat: 57.2739, lng: -5.5151 },
      { n: "Skye Bridge", lat: 57.2698, lng: -5.7238 },
      { n: "Old Man of Storr", lat: 57.5027, lng: -6.1822 },
      { n: "Portree Harbour", lat: 57.4127, lng: -6.196 },
    ],
  },
  {
    day: 8, date: "Dom 2 ago",
    title: "Isle of Skye — día completo",
    sub: "Fairy Pools · Neist Point · Dunvegan",
    driving: "~80 km en isla", overnight: "Portree, Isle of Skye",
    accent: "#061828",
    highlights: [
      { i: "💧", t: "Fairy Pools (Glen Brittle) — cascadas de agua turquesa cristalina" },
      { i: "🌊", t: "Neist Point Lighthouse — el punto más occidental de Skye, vistas al océano" },
      { i: "🐚", t: "Coral Beach, Claigan — playa de coral blanco (algas calcáreas). Irreal." },
      { i: "🏰", t: "Dunvegan Castle — el castillo habitado más antiguo del mundo (desde 1237)" },
    ],
    tickets: [
      { n: "Dunvegan Castle", p: "~18 £/p", must: true, url: "https://www.dunvegancastle.com" },
      { n: "Fairy Pools / Neist Point (parking)", p: "~3 £", must: false, url: null },
    ],
    hotels: [
      { n: "Skeabost Hotel (2ª noche)", s: 4, p: "110–150 €", note: "Quédate para disfrutar Skye con calma.", top: true, url: "https://www.skeabosthotel.com" },
      { n: "Three Chimneys Cottage", s: 5, p: "150–200 €", note: "Junto al restaurante más famoso de Skye. Para una noche especial.", url: "https://www.threechimneys.co.uk" },
    ],
    rests: [
      { n: "The Three Chimneys", ty: "Escocés · restaurante de culto", p: "€€€€", note: "Uno de los mejores de Escocia. Reserva con meses de antelación." },
      { n: "Loch Bay Restaurant, Waternish", ty: "Mariscos · Michelin ★", p: "€€€", note: "Estrella Michelin. Pequeño, íntimo, frente al loch." },
      { n: "Edinbane Lodge", ty: "Escocés rural", p: "€€", note: "Buena cocina local en ambiente de casa de campo." },
    ],
    mapCenter: [57.35, -6.4], mapZoom: 10,
    pts: [
      { n: "Fairy Pools, Glen Brittle", lat: 57.2494, lng: -6.302 },
      { n: "Neist Point Lighthouse", lat: 57.4234, lng: -6.7869 },
      { n: "Dunvegan Castle", lat: 57.4476, lng: -6.5907 },
      { n: "Coral Beach, Claigan", lat: 57.4827, lng: -6.5972 },
    ],
  },
  {
    day: 9, date: "Lun 3 ago",
    title: "Skye → Stirling",
    sub: "Regreso · Trossachs · Castillo de Stirling",
    driving: "~240 km · 3.5h", overnight: "Stirling",
    accent: "#121e0a",
    highlights: [
      { i: "🏰", t: "Castillo de Stirling — rival del de Edimburgo. Mary Queen of Scots fue coronada aquí." },
      { i: "🗽", t: "Monumento a William Wallace — la torre del Braveheart real, vistas 360°" },
      { i: "🌿", t: "Loch Katrine — corazón del Parque Nacional de los Trossachs" },
      { i: "🏘", t: "Bridge of Allan — pueblo a 15 min de Stirling, agradable para pasear" },
    ],
    // Bridge of Allan Highland Games están aquí mismo al día siguiente — nota natural
    gamesNote: {
      emoji: "⚔",
      text: "Bridge of Allan Highland Games — mañana (martes 4 ago) a solo 15 min de donde duermes. Si quieres apuntarte, el pueblo está a un paso de Stirling.",
      url: null,
      urlLabel: null,
    },
    tickets: [
      { n: "Castillo de Stirling (HES)", p: "~18 £/p", must: true, url: "https://www.historicenvironment.scot/visit-a-place/places/stirling-castle" },
      { n: "Wallace Monument", p: "~12 £/p", must: false, url: "https://www.nationalwallacemonument.com" },
    ],
    hotels: [
      { n: "Stirling Highland Hotel", s: 4, p: "90–130 €", note: "En una escuela victoriana junto al castillo. Único y con carácter.", top: true, url: "https://www.cairnhotel.co.uk/stirling" },
      { n: "Victoria Square Guest House", s: 4, p: "80–110 €", note: "B&B boutique en casa señorial. Muy bien valorado.", url: "https://www.victoriasquare.co.uk" },
      { n: "Park Lodge Hotel", s: 3, p: "65–90 €", note: "Pequeño hotel familiar con jardín, buen precio.", url: null },
    ],
    rests: [
      { n: "Portcullis Restaurant", ty: "Escocés · medieval", p: "€€", note: "Justo al lado del castillo. Ambiente medieval auténtico." },
      { n: "Artichoke Restaurant", ty: "Moderno escocés", p: "€€", note: "El favorito de los locales. Producto de Perthshire." },
      { n: "No. 2 Baker Street", ty: "Bistró encantador", p: "€€", note: "Pequeño y acogedor, buenas opciones locales." },
    ],
    mapCenter: [56.13, -3.97], mapZoom: 11,
    pts: [
      { n: "Castillo de Stirling", lat: 56.1232, lng: -3.9467 },
      { n: "Wallace Monument", lat: 56.1427, lng: -3.9183 },
      { n: "Bridge of Allan", lat: 56.1557, lng: -3.944 },
      { n: "Loch Katrine, Trossachs", lat: 56.2535, lng: -4.544 },
    ],
  },
  {
    day: 10, date: "Mar 4 ago",
    title: "Stirling · Bridge of Allan → Edimburgo",
    sub: "Highland Games mañana · Calton Hill · Victoria Street · ✈ 19:00",
    driving: "~55 km · M9", overnight: "Vuelo de regreso",
    accent: "#180f05",
    gamesNote: {
      emoji: "⚔",
      text: "Bridge of Allan Highland Games — esta mañana, a 15 minutos de Stirling. Tiempo suficiente antes de la ruta a Edimburgo y el vuelo de las 19:00.",
      url: null,
      urlLabel: null,
    },
    highlights: [
      { i: "⚔", t: "Bridge of Allan Highland Games (por la mañana, ~10–15 £ en puerta)" },
      { i: "🌅", t: "Calton Hill, Edimburgo — vistas panorámicas para la despedida" },
      { i: "🛍", t: "Victoria Street — la calle curva más bonita, compras de último momento" },
      { i: "✈", t: "Devolución del coche en EDI (mínimo 2–3h antes). Vuelo 19:00 h." },
    ],
    tickets: [
      { n: "Bridge of Allan Highland Games", p: "~10 £/p en puerta", must: false, url: null },
      { n: "Calton Hill", p: "Gratis", must: false, url: null },
    ],
    hotels: [],
    rests: [
      { n: "The Pantry, Stockbridge", ty: "Brunch escocés · el mejor de EDI", p: "€€", note: "El mejor brunch de Edimburgo para una última mañana perfecta." },
      { n: "Café St Honoré", ty: "Bistró francés-escocés", p: "€€", note: "Elegante y acogedor para comer antes del vuelo." },
    ],
    mapCenter: [55.96, -3.22], mapZoom: 11,
    pts: [
      { n: "Bridge of Allan Games", lat: 56.1557, lng: -3.944 },
      { n: "Calton Hill, Edimburgo", lat: 55.9553, lng: -3.1826 },
      { n: "Victoria Street", lat: 55.9481, lng: -3.193 },
      { n: "Aeropuerto EDI", lat: 55.9508, lng: -3.3615 },
    ],
  },
];

export const ROUTE = [
  [55.9508, -3.3615], [55.9503, -3.1883], [55.8642, -4.2518],
  [56.1026, -4.6365], [56.6818, -5.02],   [56.8191, -5.1073],
  [57.3228, -4.4419], [57.4778, -4.2247], [57.4652, -3.226],
  [57.059,  -4.1381], [57.4127, -6.196],  [56.1232, -3.9467],
  [56.1557, -3.944],  [55.9503, -3.1883], [55.9508, -3.3615],
];
