export const DAYS = [
  {
    day: 1, date: "Dom 26 jul",
    title: "Llegada — Edimburgo",
    sub: "Old Town · Castillo · Royal Mile · Calton Hill · Dean Village",
    driving: "Sin coche", overnight: "Edimburgo",
    accent: "#1e3d2a",
    highlights: [
      { i: "✈", t: "Aterrizaje EDI 09:30 — tram Airlink al centro (30 min, 8.50 £) o bus Airlink 100 (25 min, 5 £)" },
      { i: "🏰", t: "Castillo de Edimburgo (tarde) — reserva online imprescindible en verano. Los Honores de Escocia (las joyas de la corona) están aquí" },
      { i: "🏛", t: "Royal Mile de arriba abajo: Catedral de St. Giles, el Parlamento escocés y el Palacio de Holyroodhouse al fondo" },
      { i: "🧙", t: "Victoria Street — la calle curva inspiración del Callejón Diagon de Harry Potter. Tiendas independientes y ambiente único" },
      { i: "🌅", t: "Calton Hill al atardecer (15 min subiendo) — vistas panorámicas de la ciudad. Gratis y sin colas" },
      { i: "🏘", t: "Dean Village — el pueblo dentro de la ciudad, junto al río Water of Leith. 10 min a pie desde Princes Street" },
    ],
    tickets: [
      { n: "Castillo de Edimburgo", p: "~21 £/p", must: true, url: "https://www.edinburghcastle.scot" },
      { n: "Palacio de Holyroodhouse", p: "~17 £/p", must: false, url: "https://www.rct.uk/visit/palace-of-holyroodhouse" },
    ],
    hotels: [
      { n: "4 Friends House", s: 3, p: "139.15 € (reservado)", note: "Ya reservado. Alojamiento acogedor en el centro de Edimburgo.", top: true, url: null },
    ],
    rests: [
      { n: "Timberyard", ty: "Escocés moderno · km0", p: "€€€", gm: 4.5, note: "Uno de los mejores de la ciudad. Producto local de temporada." },
      { n: "The Witchery by the Castle", ty: "Escocés gourmet · gótico", p: "€€€", gm: 4.4, note: "Ambiente espectacular justo al lado del castillo. Reserva." },
      { n: "Café Royal", ty: "Mariscos · pub victoriano", p: "€€", gm: 4.3, note: "Interior del siglo XIX impresionante. Ostras y cerveza artesanal." },
    ],
    mapCenter: [55.952, -3.192], mapZoom: 14,
    pts: [
      { n: "Castillo de Edimburgo", lat: 55.9486, lng: -3.1999 },
      { n: "Royal Mile / St. Giles", lat: 55.9497, lng: -3.1918 },
      { n: "Victoria Street", lat: 55.9481, lng: -3.193 },
      { n: "Calton Hill", lat: 55.9553, lng: -3.1826 },
      { n: "Dean Village", lat: 55.9541, lng: -3.2136 },
      { n: "Palacio de Holyroodhouse", lat: 55.9523, lng: -3.1722 },
    ],
  },
  {
    day: 2, date: "Lun 27 jul",
    title: "Recoge el coche · Glasgow · Stirling · Los Kelpies",
    sub: "Recogida coche EDI · Kelvingrove · Castillo de Stirling · Kelpies",
    driving: "~2h 05 min", overnight: "Stirling",
    accent: "#12243a",
    carNote: {
      emoji: "🚗",
      text: "Recoge el coche a primera hora en el aeropuerto EDI (tram desde el centro, 30 min). Enterprise y Arnold Clark tienen oficina allí. Pide SUV automático. En Escocia se conduce por la izquierda.",
    },
    highlights: [
      { i: "🚗", t: "Recoge el coche en el aeropuerto EDI a primera hora (ver nota)" },
      { i: "🏛", t: "Kelvingrove Art Gallery & Museum en Glasgow (gratis) — impresionante colección de arte y armas medievales. 1–2h" },
      { i: "🏰", t: "Castillo de Stirling — rival del de Edimburgo, menos masificado. Las estancias reales restauradas son espectaculares" },
      { i: "🐴", t: "Los Kelpies en Falkirk (de camino) — las dos esculturas de caballos de acero de 30 metros. Una de las imágenes más icónicas de Escocia moderna. Entrada gratuita al parque" },
      { i: "🏅", t: "Commonwealth Games Glasgow (27 jul–1 ago) — si queréis ver atletismo, Scotstoun Stadium está en Glasgow. Entradas en glasgow2026.com" },
    ],
    tickets: [
      { n: "Castillo de Stirling (HES)", p: "~18 £/p", must: true, url: "https://www.historicenvironment.scot/visit-a-place/places/stirling-castle" },
      { n: "Kelvingrove Art Gallery", p: "Gratis", must: false, url: null },
      { n: "Los Kelpies (Helix Park)", p: "Gratis (parque) · ~5 £/p interior", must: false, url: "https://www.thehelix.co.uk" },
      { n: "Commonwealth Games Atletismo (opcional)", p: "20–50 £/sesión", must: false, warn: "Reserva ya si queréis ir", url: "https://www.glasgow2026.com" },
    ],
    hotels: [
      { n: "Stirling Highland Hotel", s: 4, p: "160–210 €", note: "En una escuela victoriana junto al castillo. Único y con mucho carácter.", top: true, url: "https://www.stirlinghighlandhotel.co.uk" },
      { n: "Victoria Square Guest House", s: 4, p: "130–170 €", note: "B&B boutique en casa señorial victoriana. Muy bien valorado.", url: "https://www.victoriasquare.co.uk" },
      { n: "Travelodge Stirling", s: 2, p: "80–110 €", note: "Opción económica fiable si el presupuesto aprieta.", url: "https://www.travelodge.co.uk" },
    ],
    rests: [
      { n: "Ox and Finch, Glasgow", ty: "Tapas escocesas · sharing", p: "€€", gm: 4.6, note: "Para comer en Glasgow. El más de moda. Platos pequeños para compartir." },
      { n: "Portcullis Restaurant, Stirling", ty: "Escocés · medieval", p: "€€", gm: 4.3, note: "Para cenar en Stirling. Justo al lado del castillo." },
      { n: "Artichoke Restaurant, Stirling", ty: "Moderno escocés", p: "€€", gm: 4.5, note: "El favorito de los locales en Stirling." },
    ],
    mapCenter: [56.05, -4.1], mapZoom: 9,
    pts: [
      { n: "Aeropuerto EDI (recoge coche)", lat: 55.9508, lng: -3.3615 },
      { n: "Kelvingrove Museum, Glasgow", lat: 55.8687, lng: -4.2877 },
      { n: "Los Kelpies, Falkirk", lat: 56.0198, lng: -3.7521 },
      { n: "Castillo de Stirling", lat: 56.1232, lng: -3.9467 },
    ],
  },
  {
    day: 3, date: "Mar 28 jul",
    title: "Loch Lomond",
    sub: "Luss · Navegación en el lago · Oban · Costa oeste",
    driving: "~2h 20 min", overnight: "Oban",
    accent: "#0a1e2a",
    highlights: [
      { i: "🏞", t: "Luss — el pueblo más bonito del Loch Lomond. Casitas de piedra con jardines hasta el lago. Parada obligada para fotos" },
      { i: "🚢", t: "Crucero por el Loch Lomond desde Balloch o Luss — Sweeney's Cruises opera rutas de 1h que rodean las islas. La mejor forma de ver el lago" },
      { i: "🦦", t: "Inveraray de camino a Oban — pueblo pintoresco con castillo neogótico a orillas del Loch Fyne. Parada de 1h perfecta" },
      { i: "🌊", t: "Oban — la capital de la costa oeste. Paseo por el puerto y vistas a las islas Kerrera y Mull desde la colina McCaig's Tower" },
      { i: "🦞", t: "Mariscos en Oban — las mejores ostras, gambas y langostas de Escocia. Cena obligada en el puerto" },
    ],
    tickets: [
      { n: "Crucero Loch Lomond (Sweeney's)", p: "~15 £/p", must: false, url: "https://www.sweeneyscruises.com" },
      { n: "Castillo de Inveraray", p: "~15 £/p", must: false, url: "https://www.inveraray-castle.com" },
      { n: "McCaig's Tower, Oban", p: "Gratis", must: false, url: null },
    ],
    hotels: [
      { n: "Manor House Hotel, Oban", s: 4, p: "160–210 €", note: "Casa georgiana de 1780 con vistas al puerto y a las islas. El más bonito de Oban.", top: true, url: "https://www.manorhouseoban.com" },
      { n: "The Oban Bay Hotel", s: 3, p: "120–160 €", note: "Frente al puerto, buenas vistas, cómodo y bien valorado.", url: "https://www.obanhotels.com" },
      { n: "Columba Hotel, Oban", s: 3, p: "100–140 €", note: "En el centro de Oban junto al puerto. Sólida opción económica.", url: null },
    ],
    rests: [
      { n: "Ee-Usk (Ocean Kitchen), Oban", ty: "Mariscos · sobre el puerto", p: "€€€", gm: 4.5, note: "El mejor marisco de Oban. Langostas, ostras y vieiras del día. Reserva." },
      { n: "The Seafood Shack, Oban", ty: "Mariscos · street food", p: "€€", gm: 4.7, note: "El más valorado de Oban. Langostinos y mariscos frescos en un puesto del puerto. Sin reservas." },
      { n: "Hagen's Deli & Kitchen, Oban", ty: "Café · ligero", p: "€", gm: 4.4, note: "Para un almuerzo rápido de calidad antes de seguir ruta." },
    ],
    mapCenter: [56.35, -4.9], mapZoom: 9,
    pts: [
      { n: "Luss, Loch Lomond", lat: 56.1026, lng: -4.6365 },
      { n: "Inveraray Castle", lat: 56.2328, lng: -5.0742 },
      { n: "Oban — McCaig's Tower", lat: 56.4154, lng: -5.4718 },
      { n: "Puerto de Oban", lat: 56.4115, lng: -5.4726 },
    ],
  },
  {
    day: 4, date: "Mié 29 jul",
    title: "Ruta por el valle — Glencoe · Fort William",
    sub: "Glencoe · Ben Nevis · Glenfinnan",
    driving: "~1h 15 min", overnight: "Fort William o Glencoe",
    accent: "#2a1505",
    highlights: [
      { i: "🏔", t: "Valle de Glencoe — para el coche en varios miradores. Las Three Sisters al amanecer son imbatibles. Signal Rock es la parada más evocadora" },
      { i: "⛰", t: "Ben Nevis — senderismo por la Mountain Track (5–7h, 1345m) si el tiempo acompaña. Si no, el paseo hasta el refugio de la base ya es precioso" },
      { i: "🚂", t: "Viaducto de Glenfinnan — aparca en el Visitor Centre y contempla el viaducto de piedra del tren de Harry Potter. Si cuadra el horario, pasa el Jacobite Steam Train" },
      { i: "🔒", t: "Neptune's Staircase en Banavie — la esclusa en escalera más larga del Reino Unido (8 esclusas consecutivas en el Canal de Caledonia)" },
    ],
    tickets: [
      { n: "Glencoe Visitor Centre (NTS)", p: "~7 £/p", must: false, url: "https://www.nts.org.uk/visit/places/glencoe" },
      { n: "Glenfinnan Visitor Centre (NTS)", p: "~5 £/p", must: false, url: "https://www.nts.org.uk/visit/places/glenfinnan-monument" },
      { n: "Jacobite Steam Train (si cuadra horario)", p: "~35–45 £/p", must: false, warn: "Se agota meses antes. Reserva online.", url: "https://www.westcoastrailways.co.uk/jacobite" },
    ],
    hotels: [
      { n: "Kingshouse Hotel, Glencoe", s: 4, p: "160–220 €", note: "Hotel histórico en mitad del valle. Icónico. Vistas impresionantes.", top: true, url: "https://www.kingshousehotel.co.uk" },
      { n: "The Garrison Hotel, Fort William", s: 3, p: "150–190 €", note: "El mejor valorado de Fort William (8.8/10). Desayuno excelente.", url: "https://www.thegarrisonfortwilliam.co.uk" },
      { n: "Isles of Glencoe Hotel, Ballachulish", s: 4, p: "180–240 €", note: "A orillas del Loch Linnhe. Vistas espectaculares, desayuno incluido.", url: "https://www.islesofglencoe.com" },
    ],
    rests: [
      { n: "Kingshouse Hotel Restaurant", ty: "Escocés highland", p: "€€", gm: 4.2, note: "Cordero y venado local. Ambiente rústico de montaña." },
      { n: "The Crannog Seafood, Fort William", ty: "Mariscos · sobre el lago", p: "€€", gm: 4.5, note: "El imprescindible en Fort William. Mejillones y gambas del día." },
      { n: "Ben Nevis Inn", ty: "Pub · base de montaña", p: "€", gm: 4.3, note: "Perfecto post-senderismo. En la base del Ben Nevis." },
    ],
    mapCenter: [56.75, -5.1], mapZoom: 10,
    pts: [
      { n: "Glencoe — Three Sisters", lat: 56.6818, lng: -5.02 },
      { n: "Ben Nevis (acceso)", lat: 56.7969, lng: -5.0035 },
      { n: "Viaducto de Glenfinnan", lat: 56.8726, lng: -5.4308 },
      { n: "Neptune's Staircase, Banavie", lat: 56.8468, lng: -5.1274 },
    ],
  },
  {
    day: 5, date: "Jue 30 jul",
    title: "Jacobite Train · Eilean Donan · Isle of Skye",
    sub: "Tren de Harry Potter · Castillo más fotografiado · Portree",
    driving: "~3h 15 min", overnight: "Portree, Isle of Skye",
    accent: "#061828",
    highlights: [
      { i: "🚂", t: "Jacobite Steam Train 10:15 desde Fort William — llega al viaducto de Glenfinnan a las 10:30. El tren cruza el arco de piedra sobre el valle. Si no tienes billete, ve al Visitor Centre a pie para verlo pasar" },
      { i: "🏰", t: "Eilean Donan Castle — a orillas del Loch Duich donde se unen tres lochs. El más fotografiado de Escocia. La visita interior cuenta 800 años de historia del clan MacKenzie" },
      { i: "🌉", t: "Cruzar el Skye Bridge desde Kyle of Lochalsh — el momento en que el paisaje cambia radicalmente. El puente es gratuito desde 2004" },
      { i: "⛴", t: "Alternativa más cinematográfica: ferry Mallaig → Armadale (CalMac, 30 min, ~5 £/p + ~35 £ coche). Sale varias veces al día. Reserva online — se llena en verano" },
      { i: "🎨", t: "Portree al llegar — el puerto de colores pastel es uno de los más bonitos de Escocia. Paseo junto al muelle al atardecer" },
    ],
    tickets: [
      { n: "Jacobite Steam Train (Fort William → Mallaig)", p: "~35–45 £/p", must: false, warn: "Se agota meses antes. Reserva ya en westcoastrailways.co.uk", url: "https://www.westcoastrailways.co.uk/jacobite" },
      { n: "Eilean Donan Castle", p: "~12 £/p", must: true, url: "https://www.eileandonancastle.com" },
      { n: "Ferry Mallaig→Armadale (CalMac) — si llegas por mar", p: "~5 £/p + ~35 £ coche · 30 min", must: false, warn: "Reserva online en verano", url: "https://www.calmac.co.uk" },
    ],
    hotels: [
      { n: "The Royal Hotel, Portree", s: 3, p: "200–260 €", note: "Vistas al puerto de Portree. Restaurante propio con mariscos.", top: true, url: "https://www.royalhotelportree.com" },
      { n: "Cuillin Hills Hotel", s: 4, p: "220–300 €", note: "Vistas espectaculares a los Cuillins desde Portree.", url: "https://www.cuillinhillshotel-skye.co.uk" },
      { n: "Skye Inn, Portree", s: 3, p: "160–210 €", note: "B&B muy bien valorado (4.5★). Desayuno escocés completo.", url: null },
    ],
    rests: [
      { n: "Sea Breezes, Portree", ty: "Mariscos · sin reservas", p: "€€", gm: 4.6, note: "El mejor marisco de Skye. Langostas del loch. Llega pronto." },
      { n: "Scorrybreac", ty: "Fine dining · 5 mesas", p: "€€€", gm: 4.7, note: "Menú degustación de producto de Skye. Reserva con semanas de antelación." },
      { n: "The Bosville, Portree", ty: "Bistró · casual", p: "€€", gm: 4.3, note: "Buen ambiente, vistas al puerto, buena comida local." },
    ],
    mapCenter: [57.25, -5.7], mapZoom: 9,
    pts: [
      { n: "Viaducto Glenfinnan (ver tren 10:30)", lat: 56.8726, lng: -5.4308 },
      { n: "Eilean Donan Castle", lat: 57.2739, lng: -5.5151 },
      { n: "Skye Bridge / Kyle of Lochalsh", lat: 57.2698, lng: -5.7238 },
      { n: "Portree Harbour", lat: 57.4127, lng: -6.196 },
    ],
  },
  {
    day: 6, date: "Vie 31 jul",
    title: "Ruta por la isla de Skye",
    sub: "Fairy Pools · Kilt Rock · Old Man of Storr",
    driving: "~1h 50 min", overnight: "Portree, Isle of Skye",
    accent: "#061828",
    highlights: [
      { i: "💧", t: "Fairy Pools (Glen Brittle) — cascadas de agua turquesa que brotan de los Cuillins. Las más bonitas de Escocia. Ruta fácil de 1h" },
      { i: "🪨", t: "Kilt Rock — acantilado de basalto con columnas verticales que imitan el patrón del tartán escocés. Cascada de 60m al mar. Poco masificado y espectacular" },
      { i: "🗿", t: "Old Man of Storr — la columna rocosa más icónica de Escocia. Ruta de ~2h con vistas al Loch Leathan y al mar. Aparcamiento: ~3 £" },
      { i: "🐚", t: "Coral Beach, Claigan — playa de coral blanco (algas calcáreas). Irreal, parece el Caribe en versión nórdica. 15 min a pie desde el parking" },
      { i: "🏰", t: "Dunvegan Castle (opcional) — el castillo habitado más antiguo del mundo (desde 1237). Jardines con focas en el loch" },
    ],
    tickets: [
      { n: "Old Man of Storr (aparcamiento)", p: "~3 £", must: false, url: null },
      { n: "Fairy Pools (aparcamiento)", p: "~3 £", must: false, url: null },
      { n: "Dunvegan Castle (opcional)", p: "~18 £/p", must: false, url: "https://www.dunvegancastle.com" },
    ],
    hotels: [
      { n: "The Royal Hotel, Portree (2ª noche)", s: 3, p: "200–260 €", note: "Quédate para disfrutar Skye con calma.", top: true, url: "https://www.royalhotelportree.com" },
      { n: "Skeabost House Hotel", s: 4, p: "240–320 €", note: "Casa señorial con jardines al loch. Mucho encanto.", url: "https://www.skeabosthotel.com" },
    ],
    rests: [
      { n: "The Three Chimneys", ty: "Escocés · restaurante de culto", p: "€€€€", gm: 4.7, note: "Uno de los mejores de Escocia. Reserva con meses de antelación." },
      { n: "Loch Bay Restaurant, Waternish", ty: "Mariscos · Michelin ★", p: "€€€", gm: 4.6, note: "Estrella Michelin. Pequeño, íntimo, frente al loch. Reserva." },
      { n: "Edinbane Lodge", ty: "Escocés rural", p: "€€", gm: 4.5, note: "Buena cocina local en ambiente de casa de campo." },
    ],
    mapCenter: [57.38, -6.3], mapZoom: 10,
    pts: [
      { n: "Fairy Pools, Glen Brittle", lat: 57.2494, lng: -6.302 },
      { n: "Kilt Rock", lat: 57.5499, lng: -6.1637 },
      { n: "Old Man of Storr", lat: 57.5027, lng: -6.1822 },
      { n: "Coral Beach, Claigan", lat: 57.4827, lng: -6.5972 },
    ],
  },
  {
    day: 7, date: "Sáb 1 ago",
    title: "Castillo de Urquhart · Loch Ness · Culloden · Clava Cairns",
    sub: "Lago Ness · Última batalla en suelo británico · Círculo megalítico 4000 a.C.",
    driving: "~2h 45 min", overnight: "Inverness / cerca de Aberdeen",
    accent: "#0a1828",
    gamesNote: {
      emoji: "⚔",
      text: "Newtonmore Highland Games — hoy (1 ago), a 45 min de Inverness por la A9. Lanzamiento de caber, gaitas y danza highland. Podéis parar un par de horas de camino al Loch Ness.",
      url: "https://newtonmorehighlandgames.co.uk",
      urlLabel: "Ver más ↗",
    },
    highlights: [
      { i: "⚔", t: "Newtonmore Highland Games (de camino, A9) — ver nota. El evento de Highland Games más auténtico de la zona" },
      { i: "🦕", t: "Castillo de Urquhart — ruinas del s.XIV a orillas del Loch Ness. Las almenas ofrecen las mejores vistas del lago. Busca a Nessie desde allí" },
      { i: "🚤", t: "Crucero Loch Ness (Jacobite Cruises, ~1h) — la mejor forma de entender la escala del lago: 37 km de largo, 230m de profundidad" },
      { i: "⚔", t: "Culloden Battlefield — la última batalla en suelo británico (1746). 1.300 muertos en menos de una hora. El centro de interpretación es sobrecogedor. Lleva pañuelos" },
      { i: "🪨", t: "Clava Cairns — círculo megalítico de 4.000 años a solo 1 km de Culloden. El lugar que inspiró el círculo de piedras de Outlander. Entrada gratuita, acceso libre. Mucho más impresionante de lo que parece en fotos" },
    ],
    tickets: [
      { n: "Castillo de Urquhart (HES)", p: "~12 £/p", must: true, url: "https://www.historicenvironment.scot/visit-a-place/places/urquhart-castle" },
      { n: "Culloden Battlefield (NTS)", p: "~14 £/p", must: true, url: "https://www.nts.org.uk/visit/places/culloden" },
      { n: "Crucero Loch Ness (Jacobite Cruises)", p: "~15 £/p", must: false, url: "https://www.jacobite.co.uk" },
      { n: "Clava Cairns (HES)", p: "Gratis · acceso libre", must: false, url: null },
    ],
    hotels: [
      { n: "Ness Walk Hotel, Inverness", s: 5, p: "220–300 €", note: "El mejor de Inverness, frente al río Ness. Boutique con spa.", top: true, url: "https://www.nesswalk.com" },
      { n: "Kingsmills Hotel, Inverness", s: 4, p: "160–210 €", note: "Casa señorial con spa, a 10 min del centro.", url: "https://www.kingsmillshotel.com" },
      { n: "Meldrum House, Oldmeldrum (cerca Aberdeen)", s: 4, p: "180–240 €", note: "Si prefieres avanzar hacia Aberdeen. Hotel de campo con campo de golf.", url: "https://www.meldrumhouse.com" },
    ],
    rests: [
      { n: "Ness Walk Restaurant, Inverness", ty: "Escocés moderno · boutique", p: "€€€", gm: 4.7, note: "El mejor de Inverness. Mariscos y caza de temporada. Reserva." },
      { n: "The Mustard Seed, Inverness", ty: "Escocés · iglesia convertida", p: "€€", gm: 4.4, note: "En una antigua iglesia con vistas al Ness. Gran relación calidad-precio." },
      { n: "Contrast Brasserie, Inverness", ty: "Brasserie · frente al río", p: "€€", gm: 4.3, note: "En el Glenmoriston Hotel. Menú variado a buen precio." },
    ],
    mapCenter: [57.4, -4.3], mapZoom: 10,
    pts: [
      { n: "Castillo de Urquhart", lat: 57.3228, lng: -4.4419 },
      { n: "Culloden Battlefield", lat: 57.477, lng: -4.0779 },
      { n: "Clava Cairns", lat: 57.4688, lng: -4.0308 },
      { n: "Inverness Centre", lat: 57.4778, lng: -4.2247 },
    ],
  },
  {
    day: 8, date: "Dom 2 ago",
    title: "Aberdeen · Dunnottar Castle · Costa Aberdeenshire",
    sub: "Castillo sobre el acantilado · Stonehaven · Costa del Mar del Norte",
    driving: "~2h 30 min", overnight: "Cerca de Aberdeen",
    accent: "#1a1030",
    highlights: [
      { i: "🏰", t: "Dunnottar Castle — fortaleza medieval en un promontorio rocoso de 50m sobre el Mar del Norte, a 20 min al sur de Aberdeen. Uno de los castillos más dramáticos del mundo. Aquí se custodiaron las joyas de la corona escocesa de Cromwell" },
      { i: "🏘", t: "Stonehaven — el pueblo portuario más bonito de Aberdeenshire. Puerto de pesca, fish & chips y la piscina exterior de agua de mar más grande del Reino Unido (abre en verano)" },
      { i: "🏙", t: "Aberdeen — la ciudad de granito gris. Paseo por Union Street, el Mercado de los Lunes (Castlegate) y el Old Aberdeen con su catedral de St. Machar" },
      { i: "🌊", t: "Paseo por la costa — Fyvie, Cruden Bay (las ruinas del Slains Castle, inspiración de Drácula de Bram Stoker) o simplemente la playa de Aberdeen" },
    ],
    tickets: [
      { n: "Dunnottar Castle", p: "~8 £/p", must: true, url: "https://www.dunnottarcastle.co.uk" },
      { n: "St Machar's Cathedral, Aberdeen", p: "Gratis", must: false, url: null },
    ],
    hotels: [
      { n: "Marcliffe Hotel & Spa, Aberdeen", s: 5, p: "180–250 €", note: "El mejor hotel de Aberdeen. Hotel de campo con spa a 10 min del centro.", top: true, url: "https://www.marcliffe.com" },
      { n: "Mercure Aberdeen Ardoe House", s: 4, p: "130–170 €", note: "Casa solariega victoriana con vistas. Buena relación calidad-precio.", url: "https://www.accor.com" },
      { n: "ibis Aberdeen Centre", s: 3, p: "90–120 €", note: "Económico y bien situado en el centro de Aberdeen.", url: "https://www.accor.com" },
    ],
    rests: [
      { n: "The Silver Darling, Aberdeen", ty: "Mariscos · frente al mar", p: "€€€", gm: 4.5, note: "El mejor de Aberdeen. Vistas al Mar del Norte desde el faro del puerto. Reserva." },
      { n: "The Tolbooth Restaurant, Stonehaven", ty: "Escocés · puerto histórico", p: "€€", gm: 4.4, note: "En el edificio del tolbooth del s.XVII. Mariscos frescos y carne local." },
      { n: "Café 52, Aberdeen", ty: "Bistró · europeo", p: "€€", gm: 4.5, note: "Ambiente informal, muy bien valorado por los locales. Versátil." },
    ],
    mapCenter: [57.05, -2.5], mapZoom: 10,
    pts: [
      { n: "Dunnottar Castle, Stonehaven", lat: 56.9447, lng: -2.1972 },
      { n: "Puerto de Stonehaven", lat: 56.9633, lng: -2.2097 },
      { n: "Aberdeen Centre", lat: 57.1497, lng: -2.0943 },
      { n: "St Machar's Cathedral", lat: 57.1608, lng: -2.1083 },
    ],
  },
  {
    day: 9, date: "Lun 3 ago",
    title: "St Andrews",
    sub: "La cuna del golf · Catedral medieval · Costa de Fife",
    driving: "~2h 05 min", overnight: "St Andrews",
    accent: "#0a1820",
    highlights: [
      { i: "⛳", t: "Old Course de St Andrews — el campo de golf más antiguo del mundo (s.XV). El Swilcan Bridge es la foto icónica. Puedes pasear por el campo libremente los domingos cuando no hay juego" },
      { i: "🏛", t: "Ruinas de la Catedral de St Andrews — la más grande que tuvo Escocia (s.XII). Sube a la torre de St Rule (108 escalones) para vistas panorámicas de la costa de Fife" },
      { i: "🏰", t: "Castillo de St Andrews — ruinas sobre el acantilado con una mazmorra en botella única del mundo y un túnel excavado a mano durante el asedio de 1546-47" },
      { i: "🎓", t: "Universidad de St Andrews — la más antigua de Escocia (1413) y donde estudiaron el Rey Carlos III y el Príncipe William. El campus de St Salvator's Chapel es impresionante" },
      { i: "🏘", t: "Pueblos pesqueros del East Neuk de Fife — Pittenweem, Anstruther y Crail, a 20 min en coche. Ambiente auténtico y fish & chips excepcionales en el Anstruther Fish Bar" },
    ],
    tickets: [
      { n: "Catedral de St Andrews (HES)", p: "~7 £/p (torre incluida)", must: true, url: "https://www.historicenvironment.scot/visit-a-place/places/st-andrews-castle" },
      { n: "Castillo de St Andrews (HES)", p: "~7 £/p", must: false, url: "https://www.historicenvironment.scot/visit-a-place/places/st-andrews-castle" },
      { n: "Old Course (paseo libre domingos)", p: "Gratis", must: false, url: null },
    ],
    hotels: [
      { n: "The Old Course Hotel, St Andrews", s: 5, p: "300–450 €", note: "El hotel más icónico de St Andrews, junto al Old Course. Para una noche especial.", top: true, url: "https://www.oldcoursehotel.co.uk" },
      { n: "Rufflets Country House Hotel", s: 4, p: "180–240 €", note: "Casa de campo con jardines a 10 min del centro. Muy bien valorado.", url: "https://www.rufflets.co.uk" },
      { n: "Albany Hotel, St Andrews", s: 3, p: "130–170 €", note: "B&B boutique en casas georgianas del centro. Buena relación calidad-precio.", url: null },
    ],
    rests: [
      { n: "The Seafood Restaurant, St Andrews", ty: "Mariscos · vistas al mar", p: "€€€", gm: 4.5, note: "Sobre el mar con vistas al Old Course. Mariscos de primera." },
      { n: "Anstruther Fish Bar (East Neuk)", ty: "Fish & chips · legendario", p: "€", gm: 4.6, note: "Considerado el mejor fish & chips de Escocia. Cola habitual pero vale la pena." },
      { n: "The Vine Leaf, St Andrews", ty: "Escocés · íntimo", p: "€€", gm: 4.5, note: "Restaurante pequeño con producto local excelente. Reserva." },
    ],
    mapCenter: [56.34, -2.79], mapZoom: 12,
    pts: [
      { n: "Old Course — Swilcan Bridge", lat: 56.3431, lng: -2.8029 },
      { n: "Catedral de St Andrews", lat: 56.3402, lng: -2.7922 },
      { n: "Castillo de St Andrews", lat: 56.3421, lng: -2.7941 },
      { n: "Anstruther Fish Bar (East Neuk)", lat: 56.2231, lng: -2.6986 },
    ],
  },
  {
    day: 10, date: "Mar 4 ago",
    title: "Capilla Rosslyn · Abadía Melrose · Abadía Dryburgh · Edimburgo",
    sub: "Misterio templario · Corazón de Robert the Bruce · Walter Scott · Devuelve el coche",
    driving: "~3h 45 min", overnight: "Edimburgo",
    accent: "#1a0a20",
    carNote: {
      emoji: "🚗",
      text: "Devuelve el coche hoy por la tarde en el aeropuerto de Edimburgo (EDI) antes de cenar — así el último día estáis libres para moveros en tram o a pie. Reposta antes de llegar al aeropuerto.",
    },
    highlights: [
      { i: "⛪", t: "Capilla Rosslyn (Rosslyn Chapel) — a 20 min al sur de Edimburgo. Tallas medievales enigmáticas del s.XV, vínculos con los Templarios y el Santo Grial. Hecha famosa por El Código Da Vinci. Deja al menos 1.5h" },
      { i: "🏛", t: "Abadía de Melrose — ruinas cistercienses del s.XII en los Borders escoceses. Aquí está enterrado el corazón de Robert the Bruce. Decoración gótica con gárgolas únicas" },
      { i: "🌿", t: "Scott's View — el mirador favorito de Sir Walter Scott sobre el río Tweed y los montes Eildon. A 3 km de Melrose. Para el coche 10 minutos y absorbe el paisaje" },
      { i: "🪦", t: "Abadía de Dryburgh — las ruinas más románticas de Escocia, junto al río Tweed. Sepultura de Sir Walter Scott y del Mariscal Haig. Ambiente de cuento" },
      { i: "🚗", t: "Vuelta a Edimburgo y devolución del coche en EDI por la tarde (ver nota)" },
    ],
    tickets: [
      { n: "Capilla Rosslyn", p: "~12 £/p", must: true, warn: "Reserva online recomendada en verano", url: "https://www.rosslynchapel.com" },
      { n: "Abadía de Melrose (HES)", p: "~7 £/p", must: true, url: "https://www.historicenvironment.scot/visit-a-place/places/melrose-abbey" },
      { n: "Abadía de Dryburgh (HES)", p: "~6 £/p", must: false, url: "https://www.historicenvironment.scot/visit-a-place/places/dryburgh-abbey" },
    ],
    hotels: [
      { n: "Hotel Indigo Edinburgh – Royal Mile", s: 4, p: "170–220 €", note: "Última noche en Edimburgo. Misma zona que el primer día para cerrar el círculo.", top: true, url: "https://www.ihg.com" },
      { n: "Motel One Edinburgh-Royal", s: 3, p: "120–160 €", note: "Moderno, céntrico y bien valorado. Buena opción para la última noche.", url: "https://www.motel-one.com" },
    ],
    rests: [
      { n: "Clos Maggiore Rosslyn (Roslin Glen Hotel)", ty: "Escocés · cerca de Rosslyn", p: "€€", gm: 4.3, note: "Para comer tras visitar la capilla, en el pueblo de Roslin." },
      { n: "Townhouse Restaurant, Melrose", ty: "Escocés · Borders", p: "€€", gm: 4.4, note: "El mejor de Melrose. Producto local de los Borders. Para el almuerzo." },
      { n: "The Witchery by the Castle, Edimburgo", ty: "Escocés gourmet · última cena", p: "€€€", gm: 4.4, note: "Para la cena de despedida en Edimburgo. Ambiente gótico espectacular. Reserva." },
    ],
    mapCenter: [55.8, -3.0], mapZoom: 9,
    pts: [
      { n: "Capilla Rosslyn", lat: 55.8554, lng: -3.1609 },
      { n: "Abadía de Melrose", lat: 55.5986, lng: -2.7246 },
      { n: "Scott's View", lat: 55.5923, lng: -2.6644 },
      { n: "Abadía de Dryburgh", lat: 55.5697, lng: -2.6428 },
      { n: "Aeropuerto EDI (devuelve coche)", lat: 55.9508, lng: -3.3615 },
    ],
  },
  {
    day: 11, date: "Mié 5 ago",
    title: "Última mañana en Edimburgo · Vuelo 19:10",
    sub: "Lo que quedó pendiente el día 1 · Stockbridge · ✈ 19:10",
    driving: "~30 min (tram al aeropuerto)", overnight: "Vuelo de regreso",
    accent: "#0a0f08",
    highlights: [
      { i: "🌅", t: "Mañana libre para lo que quedó pendiente el día 1 — Stockbridge, el mercado de Grassmarket, Greyfriars Kirkyard (el perro Greyfriars Bobby), o simplemente pasear sin prisa" },
      { i: "🛍", t: "Compras de último momento: Cadenhead's Whisky Shop en el Royal Mile (1842, la tienda independiente más antigua), o el mercado de Stockbridge si es domingo" },
      { i: "☕", t: "Brunch tranquilo antes de salir hacia el aeropuerto — The Pantry en Stockbridge o Peter's Yard en Quartermile" },
      { i: "✈", t: "Tram Airlink desde Princes Street al aeropuerto (30 min, 8.50 £) — salid con margen. Vuelo 19:10 h" },
    ],
    tickets: [
      { n: "Tram Airlink EDI", p: "8.50 £/p", must: true, url: null },
      { n: "Greyfriars Kirkyard", p: "Gratis", must: false, url: null },
    ],
    hotels: [],
    rests: [
      { n: "The Pantry, Stockbridge", ty: "Brunch escocés", p: "€€", gm: 4.6, note: "El mejor brunch de Edimburgo. Para una última mañana perfecta." },
      { n: "Peter's Yard, Quartermile", ty: "Café escandinavo", p: "€€", gm: 4.5, note: "Ambiente nórdico, cardamomo buns y café de especialidad. Muy recomendable." },
    ],
    mapCenter: [55.952, -3.195], mapZoom: 14,
    pts: [
      { n: "Stockbridge / The Pantry", lat: 55.9577, lng: -3.2082 },
      { n: "Greyfriars Kirkyard", lat: 55.9463, lng: -3.1915 },
      { n: "Princes Street (tram al aeropuerto)", lat: 55.9523, lng: -3.1965 },
    ],
  },
];

export const ROUTE = [
  [55.9508, -3.3615], [55.9503, -3.1883],
  [55.8687, -4.2877], [56.0198, -3.7521], [56.1232, -3.9467],
  [56.1026, -4.6365], [56.4154, -5.4718],
  [56.6818, -5.02],   [56.8191, -5.1073],
  [57.2739, -5.5151], [57.4127, -6.196],
  [57.3228, -4.4419], [57.4778, -4.2247],
  [56.9447, -2.1972], [57.1497, -2.0943],
  [56.3402, -2.7922],
  [55.8554, -3.1609], [55.9503, -3.1883], [55.9508, -3.3615],
];

export const INITIAL_EXPENSES = [
  { id: 1, concept: "Vuelos (2 personas)", total: 412.08, perPerson: 206.04, category: "✈ Transporte", date: "Pre-viaje" },
  { id: 2, concept: "ETA (entrada UK, 2 personas)", total: 48.00, perPerson: 24.00, category: "📋 Documentación", date: "Pre-viaje" },
  { id: 3, concept: "Explorer Pass (2 personas)", total: 112.81, perPerson: 56.405, category: "🎫 Entradas", date: "Pre-viaje" },
  { id: 4, concept: "Hotel 1ª noche — 4 Friends House, Edimburgo", total: 139.15, perPerson: 69.575, category: "🏨 Alojamiento", date: "26 jul" },
  { id: 5, concept: "Coche de alquiler (incl. seguro 93 €)", total: 326.55, perPerson: 163.275, category: "🚗 Coche alquiler", date: "27 jul – 4 ago" },
  { id: 6, concept: "Hotel Stirling", total: 171.95, perPerson: 85.975, category: "🏨 Alojamiento", date: "27 jul" },
  { id: 7, concept: "Hotel Oban", total: 145.95, perPerson: 72.975, category: "🏨 Alojamiento", date: "28 jul" },
  { id: 8, concept: "Hotel última noche Edimburgo", total: 124.36, perPerson: 62.18, category: "🏨 Alojamiento", date: "4 ago" },
];