export const DAYS = [
  {
    day: 1, date: "Dom 26 jul",
    title: "Llegada — Edimburgo · Recogida del coche",
    sub: "Aterrizaje 09:30 · Recoge el coche en EDI · Old Town · Grassmarket",
    driving: "0 km", overnight: "Edimburgo",
    accent: "#1e3d2a",
    highlights: [
      { i: "✈", t: "Aterrizaje EDI 09:30 — al aeropuerto llegan el tram (Airlink, 30 min, 8.50 £) y el bus Airlink 100 (25 min, 5 £). Sin coche estos dos días, moviéndose en transporte público y a pie" },
      { i: "🏰", t: "Castillo de Edimburgo (tarde) — reserva online obligatoria, las colas sin reserva son enormes en verano" },
      { i: "🥃", t: "Royal Mile de arriba abajo: pasa por la Catedral de St. Giles, el parlamento escocés y el Palacio de Holyrood" },
      { i: "🌆", t: "Grassmarket al caer la noche: cerveza local en The Beehive o The White Hart, el pub más antiguo de Edimburgo (1516)" },
      { i: "🏛", t: "Si te queda energía: sube a Calton Hill (20 min, gratis) para ver la ciudad iluminada" },
    ],
    tickets: [
      { n: "Castillo de Edimburgo", p: "~21 £/p", must: true, url: "https://www.edinburghcastle.scot" },
      { n: "Palacio de Holyrood", p: "~17 £/p", must: false, url: "https://www.rct.uk/visit/palace-of-holyroodhouse" },
    ],
    hotels: [
      { n: "Hotel Indigo Edinburgh – Royal Mile", s: 4, p: "170–220 €", note: "Diseño contemporáneo, ubicación perfecta en el Royal Mile.", top: true, url: "https://www.ihg.com" },
      { n: "Motel One Edinburgh-Royal", s: 3, p: "120–160 €", note: "Diseño moderno, céntrico y muy bien valorado. Reserva pronto.", url: "https://www.motel-one.com" },
      { n: "ibis Edinburgh Centre South Bridge", s: 3, p: "110–150 €", note: "La opción más económica bien situada junto al Royal Mile.", url: "https://www.accor.com" },
    ],
    rests: [
      { n: "Timberyard", ty: "Escocés moderno · km0", p: "€€€", gm: 4.5, note: "Uno de los mejores de la ciudad. Producto local de temporada." },
      { n: "Café Royal", ty: "Mariscos · pub victoriano", p: "€€", gm: 4.3, note: "Interior del siglo XIX impresionante. Ostras y cerveza artesanal." },
      { n: "The Grain Store", ty: "Brasserie escocesa", p: "€€", gm: 4.4, note: "Buena carne y pescado local, precio razonable." },
    ],
    mapCenter: [55.95, -3.19], mapZoom: 13,
    pts: [
      { n: "Aeropuerto EDI (recoge coche)", lat: 55.9508, lng: -3.3615 },
      { n: "Castillo de Edimburgo", lat: 55.9486, lng: -3.1999 },
      { n: "Royal Mile / St. Giles", lat: 55.9497, lng: -3.1918 },
      { n: "Grassmarket", lat: 55.9462, lng: -3.1956 },
    ],
  },
  {
    day: 2, date: "Lun 27 jul",
    title: "Edimburgo completo · ¿Excursión a Glasgow?",
    sub: "Arthur's Seat · Old Town · Holyrood · Optionally: Commonwealth Games",
    driving: "Sin coche — tren o bus si vas a Glasgow", overnight: "Edimburgo",
    accent: "#12243a",
    gamesNote: {
      emoji: "🏅",
      text: "Commonwealth Games Glasgow (27 jul–1 ago) — si queréis ir, lo más cómodo sin coche es el tren Edimburgo Waverley → Glasgow Queen St (50 min, ~15 £/p ida y vuelta). Salen cada 15 min. Scotstoun Stadium está a 30 min en metro desde el centro. Valora si merece la pena el desplazamiento o aprovechar mejor Edimburgo.",
      url: "https://www.glasgow2026.com",
      urlLabel: "Entradas Commonwealth ↗",
    },
    highlights: [
      { i: "🏔", t: "Arthur's Seat al amanecer (45 min de subida) — las mejores vistas de Edimburgo sin turistas ni coches" },
      { i: "🏛", t: "Museo Nacional de Escocia (gratis) — colección espectacular desde la Edad del Hierro hasta el whisky moderno" },
      { i: "🏙", t: "Barrio de Stockbridge — el más local de Edimburgo. Mercado dominical, cafés independientes y el río Water of Leith" },
      { i: "🚆", t: "Opción Glasgow: tren desde Waverley (50 min, ~15 £/p ida y vuelta, salen cada 15 min) → Kelvingrove gratis + Commonwealth Games tarde" },
      { i: "🍺", t: "Noche en el Grassmarket o en Rose Street — la calle de los pubs más famosa de Escocia" },
    ],
    tickets: [
      { n: "Commonwealth Games Atletismo (si vais)", p: "20–50 £/sesión", must: false, warn: "Reserva ya si decidís ir", url: "https://www.glasgow2026.com" },
      { n: "Tren EDI → Glasgow (ScotRail)", p: "~12–18 £/p ida y vuelta", must: false, url: "https://www.scotrail.co.uk" },
      { n: "Museo Nacional de Escocia", p: "Gratis", must: false, url: null },
    ],
    hotels: [
      { n: "Hotel Indigo Edinburgh – Royal Mile", s: 4, p: "2ª noche", note: "Misma habitación — dos noches seguidas en Edimburgo.", top: true, url: "https://www.ihg.com" },
    ],
    rests: [
      { n: "The Pantry, Stockbridge", ty: "Brunch · el mejor de EDI", p: "€€", gm: 4.6, note: "El favorito de los locales. Si te quedas en Edimburgo, desayuna aquí." },
      { n: "Ox and Finch, Glasgow", ty: "Tapas escocesas · sharing", p: "€€", gm: 4.6, note: "Si vas a Glasgow: el más de moda, platos pequeños para compartir." },
      { n: "Timberyard, Edimburgo", ty: "Escocés moderno · cena", p: "€€€", gm: 4.5, note: "Para cenar en Edimburgo si os quedáis. Reserva con antelación." },
    ],
    mapCenter: [55.9, -3.6], mapZoom: 10,
    pts: [
      { n: "Arthur's Seat, Edimburgo", lat: 55.9442, lng: -3.1611 },
      { n: "Museo Nacional de Escocia", lat: 55.9469, lng: -3.1910 },
      { n: "Stockbridge", lat: 55.9577, lng: -3.2082 },
      { n: "Glasgow Queen St (opcional)", lat: 55.8636, lng: -4.2507 },
    ],
  },
  {
    day: 3, date: "Mar 28 jul",
    title: "Edimburgo → Stirling · Recoge el coche → Glencoe",
    sub: "Recogida coche Stirling · Castillo · Trossachs · Primeros Highlands",
    driving: "~170 km desde Stirling · 2.5h", overnight: "Glencoe / Ballachulish",
    accent: "#2a1505",
    carNote: {
      emoji: "🚗",
      text: "Recoge el coche en Stirling al llegar en tren desde Edimburgo (35 min, ~10 £/p). Enterprise, Arnold Clark y Hertz tienen oficinas en Stirling ciudad. Pide SUV automático — imprescindible para las pistas de los Highlands. Recuerda: en Escocia se conduce por la izquierda.",
    },
    highlights: [
      { i: "🚆", t: "Tren Edimburgo Waverley → Stirling (35 min, ~10 £/p) — recoge el coche al llegar" },
      { i: "🏰", t: "Castillo de Stirling — rival directo del de Edimburgo, menos masificado y más auténtico. Mary Queen of Scots fue coronada aquí" },
      { i: "🏰", t: "Castillo Doune (20 min de Stirling) — usado en Monty Python y Los Caballeros de la Mesa Cuadrada y en Outlander. Visita rápida que merece la pena" },
      { i: "🌿", t: "Trossachs y Loch Katrine — el parque nacional más accesible. Verde intenso, silencio total. País de Rob Roy MacGregor" },
      { i: "🏞", t: "Luss (Loch Lomond) — el pueblo más bonito del parque nacional, parada obligada para fotos" },
      { i: "🏔", t: "Valle de Glencoe al atardecer — las Three Sisters se tiñen de naranja. La foto del viaje" },
    ],
    tickets: [
      { n: "Castillo de Stirling (HES)", p: "~18 £/p", must: true, url: "https://www.historicenvironment.scot/visit-a-place/places/stirling-castle" },
      { n: "Castillo Doune (HES)", p: "~10 £/p", must: false, url: "https://www.historicenvironment.scot/visit-a-place/places/doune-castle" },
      { n: "Glencoe Visitor Centre (NTS)", p: "~7 £/p", must: false, url: "https://www.nts.org.uk/visit/places/glencoe" },
    ],
    hotels: [
      { n: "Isles of Glencoe Hotel", s: 4, p: "180–240 €", note: "A orillas del Loch Linnhe en Ballachulish. Vistas espectaculares, desayuno incluido.", top: true, url: "https://www.islesofglencoe.com" },
      { n: "Kingshouse Hotel", s: 4, p: "160–220 €", note: "Hotel histórico en mitad del valle de Glencoe. Icónico.", url: "https://www.kingshousehotel.co.uk" },
      { n: "Ballachulish Hotel", s: 3, p: "130–170 €", note: "Pub-hotel acogedor con buena cocina local y vistas al loch.", url: null },
    ],
    rests: [
      { n: "Kingshouse Hotel Restaurant", ty: "Escocés highland", p: "€€", gm: 4.2, note: "Cordero y venado local. Ambiente rústico de montaña." },
      { n: "Isles of Glencoe Restaurant", ty: "Escocés · vistas al loch", p: "€€", gm: 4.3, note: "Cocina sólida con vistas al Loch Linnhe. Mariscos frescos." },
      { n: "Glencoe Café", ty: "Café ligero", p: "€", gm: 4.4, note: "Sopas caseras y tartas. Perfecto para reponer fuerzas." },
    ],
    mapCenter: [56.3, -4.6], mapZoom: 8,
    pts: [
      { n: "Castillo de Stirling", lat: 56.1232, lng: -3.9467 },
      { n: "Castillo Doune", lat: 56.1978, lng: -4.0578 },
      { n: "Loch Katrine, Trossachs", lat: 56.2535, lng: -4.544 },
      { n: "Luss, Loch Lomond", lat: 56.1026, lng: -4.6365 },
      { n: "Glencoe — Three Sisters", lat: 56.6818, lng: -5.02 },
    ],
  },
  {
    day: 4, date: "Mié 29 jul",
    title: "Fort William · Ben Nevis · Jacobite Train",
    sub: "El techo de Gran Bretaña · El tren de Harry Potter",
    driving: "~40 km local", overnight: "Fort William",
    accent: "#082018",
    highlights: [
      { i: "⛰", t: "Ben Nevis — senderismo por la Mountain Track (5–7h, 1345m). Si no apetece subir, el paseo por el glen hasta el albergue base ya merece la pena" },
      { i: "🚂", t: "Jacobite Steam Train de Fort William a Mallaig — cruza el icónico Viaducto de Glenfinnan (el de Harry Potter). El trayecto de ida dura 2h" },
      { i: "🦞", t: "Mallaig — puerto de pescadores al final del trayecto. Las gambas y langostas son extraordinarias. Come junto al muelle" },
      { i: "🌊", t: "Desde Mallaig puedes divisar las islas Eigg y Rùm. Si tienes tiempo, el ferry a Knoydart es una experiencia única" },
      { i: "🔒", t: "Neptune's Staircase en Banavie — la esclusa en escalera más larga del Reino Unido (8 esclusas consecutivas)" },
    ],
    tickets: [
      { n: "Jacobite Steam Train", p: "~35–45 £/p", must: true, warn: "Se agota meses antes. Reserva ya.", url: "https://www.westcoastrailways.co.uk/jacobite" },
      { n: "Ben Nevis (libre acceso)", p: "Gratis · botas impermeables imprescindibles", must: false, url: null },
    ],
    hotels: [
      { n: "The Garrison Hotel", s: 3, p: "150–190 €", note: "El mejor valorado de Fort William (8.8/10 Booking). Desayuno excelente.", top: true, url: "https://www.thegarrisonfortwilliam.co.uk" },
      { n: "Glenlochy Guest House", s: 3, p: "120–150 €", note: "B&B junto al río Nevis, muy bien valorado (9.2). Ambiente tranquilo.", url: null },
      { n: "Premier Inn Fort William", s: 3, p: "110–140 €", note: "Fiable y limpio. La opción más predecible y económica.", url: "https://www.premierinn.com" },
    ],
    rests: [
      { n: "The Crannog Seafood Restaurant", ty: "Mariscos · sobre el lago", p: "€€", gm: 4.5, note: "El imprescindible en Fort William. Mejillones y gambas del día." },
      { n: "Garrison West", ty: "Grill · casual", p: "€€", gm: 4.2, note: "Buena carne local, ambiente relajado." },
      { n: "Ben Nevis Inn", ty: "Pub · base de montaña", p: "€", gm: 4.3, note: "Perfecto post-senderismo. En la mismísima base del Ben Nevis." },
    ],
    mapCenter: [56.82, -5.15], mapZoom: 10,
    pts: [
      { n: "Ben Nevis (acceso)", lat: 56.7969, lng: -5.0035 },
      { n: "Estación Fort William (Jacobite)", lat: 56.8191, lng: -5.1073 },
      { n: "Viaducto de Glenfinnan", lat: 56.8726, lng: -5.4308 },
      { n: "Mallaig (final del trayecto)", lat: 57.0059, lng: -5.8285 },
      { n: "Neptune's Staircase, Banavie", lat: 56.8468, lng: -5.1274 },
    ],
  },
  {
    day: 5, date: "Jue 30 jul",
    title: "Fort William → Inverness",
    sub: "Great Glen · Loch Ness · Culloden",
    driving: "~105 km · A82 · 1.5h", overnight: "Inverness",
    accent: "#0a1828",
    highlights: [
      { i: "🦕", t: "Castillo de Urquhart a orillas del Loch Ness — las ruinas se asoman al lago. Busca a Nessie desde las almenas" },
      { i: "🚤", t: "Crucero por el Loch Ness desde Drumnadrochit (~1h) — la mejor forma de entender la escala del lago" },
      { i: "⚔", t: "Culloden Battlefield — la última batalla campal en suelo británico (1746). El centro de interpretación es excelente. Lleva pañuelos" },
      { i: "🏛", t: "Fort George (opcional, 30 min de Inverness) — fortaleza del s.XVIII perfectamente conservada, entrada a orillas del Moray Firth" },
      { i: "🏙", t: "Inverness: paseo por el río Ness, mercado victoriano cubierto y el Victorian Market para compras locales" },
    ],
    tickets: [
      { n: "Castillo de Urquhart (HES)", p: "~12 £/p", must: true, url: "https://www.historicenvironment.scot/visit-a-place/places/urquhart-castle" },
      { n: "Culloden Battlefield (NTS)", p: "~14 £/p", must: true, url: "https://www.nts.org.uk/visit/places/culloden" },
      { n: "Crucero Loch Ness (Jacobite Cruises)", p: "~15 £/p", must: false, url: "https://www.jacobite.co.uk" },
    ],
    hotels: [
      { n: "Ness Walk Hotel", s: 5, p: "220–300 €", note: "El mejor de Inverness, frente al río Ness. Boutique con spa.", top: true, url: "https://www.nesswalk.com" },
      { n: "Kingsmills Hotel", s: 4, p: "160–210 €", note: "Casa señorial con spa, a 10 min del centro.", url: "https://www.kingsmillshotel.com" },
      { n: "Columba Hotel", s: 3, p: "130–170 €", note: "Frente al río Ness en pleno centro. Buena relación calidad-precio.", url: null },
    ],
    rests: [
      { n: "Ness Walk Restaurant", ty: "Escocés moderno · boutique", p: "€€€", gm: 4.7, note: "El mejor de Inverness. Mariscos y caza de temporada. Reserva." },
      { n: "The Mustard Seed", ty: "Escocés · iglesia convertida", p: "€€", gm: 4.4, note: "En una antigua iglesia con vistas al Ness. Gran relación calidad-precio." },
      { n: "Contrast Brasserie", ty: "Brasserie · frente al río", p: "€€", gm: 4.3, note: "En el Glenmoriston Hotel. Menú variado a buen precio." },
    ],
    mapCenter: [57.38, -4.4], mapZoom: 10,
    pts: [
      { n: "Castillo de Urquhart", lat: 57.3228, lng: -4.4419 },
      { n: "Culloden Battlefield", lat: 57.477, lng: -4.0779 },
      { n: "Fort George", lat: 57.5784, lng: -4.0591 },
      { n: "Inverness Centre", lat: 57.4778, lng: -4.2247 },
    ],
  },
  {
    day: 6, date: "Vie 31 jul",
    title: "Inverness → Speyside · Whisky Trail",
    sub: "La meca del single malt escocés",
    driving: "~80 km · A9/A95 · 1.5h", overnight: "Speyside",
    accent: "#201000",
    highlights: [
      { i: "🥃", t: "The Macallan — arquitectura espectacular del estudio Rogers Stirk Harbour. La visita a las bodegas bajo tierra es única. Reserva online imprescindible" },
      { i: "🥃", t: "Glenfarclas — destilería familiar desde 1836, una de las pocas no vendidas a multinacional. Cata de 6 expresiones diferentes en el Ship's Room" },
      { i: "🥃", t: "Glenfiddich (en Dufftown) — la más visitada del mundo. Arquitectura del s.XIX intacta. Buena para iniciarse en el whisky" },
      { i: "🏞", t: "Speyside Way — paseo de 1–2h junto al río Spey entre Aberlour y Craigellachie. Salmones en el río si vas con suerte" },
      { i: "🎶", t: "Pub de Aberlour al caer la noche — sesiones de música folk escocesa espontáneas los viernes en verano" },
    ],
    tickets: [
      { n: "The Macallan Experience", p: "~25–50 £/p", must: true, warn: "Reserva online imprescindible", url: "https://www.themacallan.com/visit" },
      { n: "Glenfarclas Distillery + Cata", p: "~15 £/p", must: true, url: "https://www.glenfarclas.com/visit" },
      { n: "Glenfiddich Distillery Tour", p: "~15 £/p", must: false, url: "https://www.glenfiddich.com/distillery" },
    ],
    hotels: [
      { n: "Craigellachie Hotel", s: 4, p: "170–230 €", note: "Victoriano icónico. El Quaich Bar tiene 1.000+ referencias de whisky. El mejor de la zona.", top: true, url: "https://www.craigellachiehotel.co.uk" },
      { n: "Mash Tun B&B, Aberlour", s: 4, p: "150–190 €", note: "B&B temático del whisky junto al río Spey. Muy bien valorado.", url: "https://www.mashtun-aberlour.com" },
      { n: "Grant Arms Hotel, Grantown-on-Spey", s: 3, p: "120–160 €", note: "Hotel histórico con encanto y buen pub. Más asequible.", url: "https://www.grantarmshotel.com" },
    ],
    rests: [
      { n: "The Copper Dog (Craigellachie)", ty: "Pub gourmet · whisky bar", p: "€€", gm: 4.4, note: "La mejor selección de whiskies. Comida de pub excelente." },
      { n: "The Mash Tun", ty: "Escocés íntimo", p: "€€", gm: 4.5, note: "Cenas caseras con productos locales. Ambiente acogedor." },
      { n: "Dowans Hotel Restaurant", ty: "Escocés clásico · junto al Spey", p: "€€", gm: 4.2, note: "Buena relación calidad-precio en entorno precioso." },
    ],
    mapCenter: [57.42, -3.25], mapZoom: 11,
    pts: [
      { n: "The Macallan Distillery", lat: 57.4769, lng: -3.2069 },
      { n: "Glenfarclas Distillery", lat: 57.3919, lng: -3.3628 },
      { n: "Glenfiddich, Dufftown", lat: 57.4432, lng: -3.1279 },
      { n: "Aberlour (Speyside Way)", lat: 57.4652, lng: -3.226 },
    ],
  },
  {
    day: 7, date: "Sáb 1 ago",
    title: "Speyside → Isle of Skye",
    sub: "Eilean Donan · Kilt Rock · Old Man of Storr · Portree",
    driving: "~220 km · 3h", overnight: "Portree, Isle of Skye",
    accent: "#061828",
    gamesNote: {
      emoji: "⚔",
      text: "Newtonmore Highland Games — hoy, a solo 30 min fuera de tu ruta (A9). Lanzamiento de caber, gaitas y danza highland. Puedes parar un par de horas de camino a Skye sin destrozar el día.",
      url: "https://newtonmorehighlandgames.co.uk",
      urlLabel: "Ver más ↗",
    },
    highlights: [
      { i: "⚔", t: "Newtonmore Highland Games (opcional, 30 min fuera de ruta A9) — ver nota" },
      { i: "🏰", t: "Eilean Donan Castle — el más fotografiado de Escocia. La visita interior merece la pena, no solo la foto exterior" },
      { i: "🌉", t: "Skye por carretera (recomendado): cruzar el Skye Bridge desde Kyle of Lochalsh — gratis, dramático, el paisaje cambia radicalmente al cruzar" },
      { i: "⛴", t: "Skye por ferry (alternativa más bonita): Mallaig → Armadale (30 min, CalMac Ferries, ~5 £/p + ~35 £ coche). Sale varias veces al día. Reserva con antelación en verano — se llena. Combina bien si haces el Jacobite Train el día anterior hasta Mallaig" },
      { i: "🪨", t: "Kilt Rock — acantilado de basalto en forma de tartán escocés con cascada al mar. Imprescindible y muy poco masificado" },
      { i: "🗿", t: "Old Man of Storr — la columna rocosa más icónica de Escocia. Ruta de ~2h con vistas al Loch Leathan" },
    ],
    tickets: [
      { n: "Eilean Donan Castle", p: "~12 £/p", must: true, url: "https://www.eileandonancastle.com" },
      { n: "Ferry Mallaig→Armadale (CalMac) — si llegas por mar", p: "~5 £/p + ~35 £ coche · 30 min", must: false, warn: "Reserva online — se llena en verano", url: "https://www.calmac.co.uk" },
      { n: "Newtonmore Games (si paras)", p: "~10–15 £/p en puerta", must: false, url: "https://newtonmorehighlandgames.co.uk" },
      { n: "Old Man of Storr (aparcamiento)", p: "~3 £", must: false, url: null },
    ],
    hotels: [
      { n: "The Royal Hotel, Portree", s: 3, p: "200–260 €", note: "Vistas al puerto de Portree. Restaurante propio con mariscos. Bien ubicado.", top: true, url: "https://www.royalhotelportree.com" },
      { n: "Cuillin Hills Hotel", s: 4, p: "220–300 €", note: "Vistas espectaculares a los Cuillins. Más caro pero con encanto propio.", url: "https://www.cuillinhillshotel-skye.co.uk" },
      { n: "Skye Inn, Portree", s: 3, p: "160–210 €", note: "B&B muy bien valorado (4.5★). Habitaciones nuevas y desayuno escocés completo.", url: null },
    ],
    rests: [
      { n: "Sea Breezes, Portree", ty: "Mariscos · sin reservas", p: "€€", gm: 4.6, note: "El mejor marisco de Skye. Langostas del loch. Llega pronto, no admite reservas." },
      { n: "Scorrybreac", ty: "Fine dining · 5 mesas", p: "€€€", gm: 4.7, note: "Menú degustación de producto de Skye. Reserva con semanas de antelación." },
      { n: "The Bosville, Portree", ty: "Bistró · casual", p: "€€", gm: 4.3, note: "Buen ambiente, vistas al puerto, buena comida local." },
    ],
    mapCenter: [57.3, -5.8], mapZoom: 9,
    pts: [
      { n: "Newtonmore (Highland Games, opcional)", lat: 57.059, lng: -4.1381 },
      { n: "Eilean Donan Castle", lat: 57.2739, lng: -5.5151 },
      { n: "Skye Bridge", lat: 57.2698, lng: -5.7238 },
      { n: "Kilt Rock", lat: 57.5499, lng: -6.1637 },
      { n: "Old Man of Storr", lat: 57.5027, lng: -6.1822 },
      { n: "Portree Harbour", lat: 57.4127, lng: -6.196 },
    ],
  },
  {
    day: 8, date: "Dom 2 ago",
    title: "Isle of Skye — día completo",
    sub: "Fairy Pools · Neist Point · Dunvegan · Quiraing",
    driving: "~80 km en isla", overnight: "Portree, Isle of Skye",
    accent: "#061828",
    highlights: [
      { i: "💧", t: "Fairy Pools (Glen Brittle) — cascadas turquesa que brotan de los Cuillins. Aguas cristalinas en las que algunos se bañan (si te atreves con 10°C)" },
      { i: "🌊", t: "Neist Point Lighthouse — el punto más occidental de Skye. Silencio total, vistas al océano Atlántico y posible avistamiento de ballenas y delfines" },
      { i: "🏔", t: "Quiraing — laberinto de torres y acantilados en el norte de Trotternish. Paisaje lunar. Ruta circular de ~4km con desnivel moderado" },
      { i: "🐚", t: "Coral Beach, Claigan — playa de coral blanco (algas calcáreas calcificadas). Irreal, parece el Caribe en versión nórdica" },
      { i: "🏰", t: "Dunvegan Castle — habitado sin interrupción desde 1237 por el clan MacLeod. Jardines preciosos con focas en el loch" },
    ],
    tickets: [
      { n: "Dunvegan Castle", p: "~18 £/p", must: true, url: "https://www.dunvegancastle.com" },
      { n: "Fairy Pools / Neist / Quiraing (parking)", p: "~3 £/punto", must: false, url: null },
    ],
    hotels: [
      { n: "The Royal Hotel, Portree (2ª noche)", s: 3, p: "200–260 €", note: "Quédate para disfrutar Skye con calma.", top: true, url: "https://www.royalhotelportree.com" },
      { n: "Skeabost House Hotel", s: 4, p: "240–320 €", note: "Casa señorial con jardines al loch. Mucho encanto, más alejado.", url: "https://www.skeabosthotel.com" },
    ],
    rests: [
      { n: "The Three Chimneys", ty: "Escocés · restaurante de culto", p: "€€€€", gm: 4.7, note: "Uno de los mejores de Escocia. Menú degustación de Skye. Reserva con meses de antelación." },
      { n: "Loch Bay Restaurant, Waternish", ty: "Mariscos · Michelin ★", p: "€€€", gm: 4.6, note: "Estrella Michelin. Pequeño, íntimo, frente al loch." },
      { n: "Edinbane Lodge", ty: "Escocés rural", p: "€€", gm: 4.5, note: "Buena cocina local en ambiente de casa de campo." },
    ],
    mapCenter: [57.38, -6.45], mapZoom: 10,
    pts: [
      { n: "Fairy Pools, Glen Brittle", lat: 57.2494, lng: -6.302 },
      { n: "Neist Point Lighthouse", lat: 57.4234, lng: -6.7869 },
      { n: "Quiraing", lat: 57.6386, lng: -6.2674 },
      { n: "Coral Beach, Claigan", lat: 57.4827, lng: -6.5972 },
      { n: "Dunvegan Castle", lat: 57.4476, lng: -6.5907 },
    ],
  },
  {
    day: 9, date: "Lun 3 ago",
    title: "Skye → Stirling",
    sub: "Regreso · Rannoch Moor · Loch Lomond · Stirling",
    driving: "~240 km · A87 → A82 → M9 · 3.5h", overnight: "Stirling",
    accent: "#121e0a",
    gamesNote: {
      emoji: "⚔",
      text: "Bridge of Allan Highland Games — mañana (mar 4 ago) a solo 15 min de donde duermes esta noche. Si os apetece empezar el último día con caber y gaitas, está en el camino.",
      url: null, urlLabel: null,
    },
    highlights: [
      { i: "🌫", t: "Rannoch Moor de camino — para el coche y sal 10 minutos. El silencio y la desolación de la llanura son difíciles de describir" },
      { i: "🏰", t: "Castillo de Stirling — visita interior completa si no lo viste el día 3. Las estancias reales restauradas están impresionantes" },
      { i: "🗽", t: "Monumento a William Wallace — la torre del Braveheart real. Sube los 246 escalones para vistas de 360° hacia los Highlands y el Forth" },
      { i: "🌿", t: "Paseo por Bridge of Allan — el pueblo más elegante de la zona, a 15 min de Stirling. Tiendas, cafés y el río Allan" },
      { i: "⚔", t: "Bridge of Allan Highland Games mañana — a 15 min, muy local y auténtico" },
    ],
    tickets: [
      { n: "Castillo de Stirling (HES)", p: "~18 £/p", must: true, url: "https://www.historicenvironment.scot/visit-a-place/places/stirling-castle" },
      { n: "Wallace Monument", p: "~12 £/p", must: false, url: "https://www.nationalwallacemonument.com" },
    ],
    hotels: [
      { n: "Stirling Highland Hotel", s: 4, p: "160–210 €", note: "En una escuela victoriana junto al castillo. Único y con carácter.", top: true, url: "https://www.stirlinghighlandhotel.co.uk" },
      { n: "Victoria Square Guest House", s: 4, p: "130–170 €", note: "B&B boutique en casa señorial victoriana. Muy bien valorado.", url: "https://www.victoriasquare.co.uk" },
      { n: "Travelodge Stirling", s: 2, p: "90–120 €", note: "Opción económica si el presupuesto aprieta esta noche.", url: "https://www.travelodge.co.uk" },
    ],
    rests: [
      { n: "Portcullis Restaurant", ty: "Escocés · medieval", p: "€€", gm: 4.3, note: "Justo al lado del castillo. Ambiente medieval auténtico." },
      { n: "Artichoke Restaurant", ty: "Moderno escocés", p: "€€", gm: 4.5, note: "El favorito de los locales. Producto de Perthshire." },
      { n: "No. 2 Baker Street", ty: "Bistró encantador", p: "€€", gm: 4.4, note: "Pequeño y acogedor, buenas opciones locales." },
    ],
    mapCenter: [56.2, -4.1], mapZoom: 9,
    pts: [
      { n: "Rannoch Moor", lat: 56.6537, lng: -4.7456 },
      { n: "Castillo de Stirling", lat: 56.1232, lng: -3.9467 },
      { n: "Wallace Monument", lat: 56.1427, lng: -3.9183 },
      { n: "Bridge of Allan (Games mañana)", lat: 56.1557, lng: -3.944 },
    ],
  },
  {
    day: 10, date: "Mar 4 ago",
    title: "Stirling → Edimburgo · Vuelo 19:00",
    sub: "Bridge of Allan Games · Calton Hill · Devolución coche · ✈",
    driving: "~55 km · M9", overnight: "Vuelo de regreso",
    accent: "#180f05",
    gamesNote: {
      emoji: "⚔",
      text: "Bridge of Allan Highland Games — esta mañana, a 15 min de Stirling. Tiempo de sobra para ver caber y gaitas antes de ponerse en ruta hacia Edimburgo con el vuelo a las 19:00.",
      url: null, urlLabel: null,
    },
    carNote: {
      emoji: "🚗",
      text: "Devuelve el coche en el aeropuerto de Edimburgo (EDI) antes de embarcar. Llega con al menos 2–3 horas de antelación. Reposta justo antes del aeropuerto — repostar en la gasolinera de la empresa sale el doble de caro.",
    },
    highlights: [
      { i: "⚔", t: "Bridge of Allan Highland Games (mañana, ~10–15 £ en puerta) — tu último Highland Games del viaje" },
      { i: "🌅", t: "Calton Hill en Edimburgo — la subida más fácil (15 min) con las mejores vistas de la ciudad. Perfecto para la última foto" },
      { i: "🛍", t: "Victoria Street — la calle curva e inspiración del Callejón Diagon. Tiendas de whisky, tartán y recuerdos de calidad" },
      { i: "✈", t: "Devolución coche en EDI (ver nota) · mínimo 2–3h antes · Vuelo 19:00 h" },
    ],
    tickets: [
      { n: "Bridge of Allan Highland Games", p: "~10 £/p en puerta", must: false, url: null },
      { n: "Calton Hill", p: "Gratis", must: false, url: null },
    ],
    hotels: [],
    rests: [
      { n: "The Pantry, Stockbridge", ty: "Brunch escocés", p: "€€", gm: 4.6, note: "El mejor brunch de Edimburgo para una última mañana perfecta." },
      { n: "Café St Honoré", ty: "Bistró francés-escocés", p: "€€", gm: 4.5, note: "Elegante y acogedor para comer antes del vuelo." },
    ],
    mapCenter: [55.96, -3.22], mapZoom: 11,
    pts: [
      { n: "Bridge of Allan Games", lat: 56.1557, lng: -3.944 },
      { n: "Calton Hill, Edimburgo", lat: 55.9553, lng: -3.1826 },
      { n: "Victoria Street", lat: 55.9481, lng: -3.193 },
      { n: "Aeropuerto EDI (devuelve coche)", lat: 55.9508, lng: -3.3615 },
    ],
  },
];

export const ROUTE = [
  [55.9508, -3.3615], [55.9503, -3.1883], [55.8642, -4.2518],
  [56.1232, -3.9467], [56.1978, -4.0578], [56.2535, -4.544],
  [56.1026, -4.6365], [56.6818, -5.02],   [56.8191, -5.1073],
  [57.3228, -4.4419], [57.4778, -4.2247], [57.4652, -3.226],
  [57.059,  -4.1381], [57.4127, -6.196],  [56.1232, -3.9467],
  [56.1557, -3.944],  [55.9503, -3.1883], [55.9508, -3.3615],
];

export const INITIAL_EXPENSES = [
  { id: 1, concept: "Vuelos (2 personas)", total: 412.08, perPerson: 206.04, category: "✈ Transporte", date: "Pre-viaje" },
  { id: 2, concept: "ETA (entrada UK, 2 personas)", total: 48.00, perPerson: 24.00, category: "📋 Documentación", date: "Pre-viaje" },
];
